export default {
  _comment_0: "billingPage",
  amount_payed: "Importo pagato",
  last_payment_date: "Data dell'ultimo pagamento",
  order_completed: "ORDINI PAGATI AL 100%",
  order_date: "Data del documento di consegna",
  orders_with_payments_not_do_it: "ORDINI CON PAGAMENTI IN SOSPESO",
  pending_collection: "In sospeso",
  selected_optic: "Ottiche selezionate",
  subtitle_order_completed:
    "Ordini che sono stati pagati al 100% e non sono in una transazione.",
  subtitle_orders_with_payments_not_do_it:
    "Elenco degli ordini in attesa di pagamento",
  total_price: "Prezzo totale",

  _comment_1: "blockByCountryPage",
  title_block_by_country: "Bloccare orari per paese",
  select_country: "",
  end_date_must_be_after_start_date:
    "La data finale deve essere più lunga della data iniziale.",

  _comment_2: "customerPage",
  myCustomersSearch: "Cerca i miei clienti",
  customersSearch: "Cerca Clienti",
  myOptics: "Le mie ottiche",
  search_customer: "Cerca Cliente",

  _comment_3: "formPage",
  "1CU-C17": "Clip Martin Foresta Verde",
  "1CU-C1P12": "Clip Martin Kenya",
  "1CU-C1P13": "Clip Martin Highlands",
  _comment_4: "new translations 👆",
  "1CU-C18": "Clip Martin Cioccolato",
  "1CU-C1P21": "Clip Martin Black Flowers",
  "1CU-C19": "Clip Martin Red Passion",
  "1CU-C1P20": "Clip Martin Valparaíso",
  "1TU-C18": "Varillas Cioccolato",
  "1TU-P21": "Varillas Black Flowers",
  "1TU-C19": "Varillas Red Passion",
  "1TU-P20": "Varillas Valparaíso",
  "1TU-C17": "Varillas Foresta Verde",
  "1TU-P12": "Varillas Kenya",
  "1TU-P13": "Varillas Highlands",
  "2CU-C18": "Clip Memphis Cioccolato",
  "2CU-C1P21": "Clip Memphis Black Flowers",
  "2CU-C19": "Clip Memphis Red Passion",
  "2CU-C1P20": "Clip Memphis Valparaíso",
  "2CU-C17": "Clip Memphis Foresta Verde",
  "2CU-C1P12": "Clip Memphis Kenya",
  "2CU-C1P13": "Clip Memphis Highlands",
  "1CU-C1 + 1CU-DA": "Clip base nera Martin Solar Blue Gradient polarizzata",
  "1CU-C1 + 1CU-DC": "Clip Martin Solare Azzurro Chiaro Polarizzato",
  "1CU-C1 + 1CU-DF": "Clip Martin Solare Vino Graduato Polarizzato",
  "1CU-C1 + 1CU-DL": "Martin Solar Black Base Clip Light Lilla Polarizzato",
  "1CU-C1 + 1CU-DM": "Clip Martin Solare Marrone Graduato Polarizzato",
  "1CU-C1 + 1CU-EC": "Clip Martin Solare Rame Riflettente Polarizzato",
  "1CU-C1 + 1CU-EL": "Clip Martin Solare Viola Riflettente Polarizzato",
  "1CU-C1 + 1CU-EP": "Clip Martin Solare Riflettente Polarizzato",
  "1CU-C1 + 1CU-ER": "Clip Martin Solare Fucsia Riflettente Polarizzato",
  "1CU-C1 + 1CU-EV": "Clip Martin  Solare Verde Riflettente Polarizzato",
  "1CU-C10": "Clip Martin Marpat",
  "1CU-C11": "Clip Martin Senape",
  "1CU-C12": "Clip Martin Iced Coffee",
  "1CU-C13": "Clip Martin Oliver",
  "1CU-C14": "Clip Martin Valentina",
  "1CU-C15": "Clip Martin Red Sunset",
  "1CU-C16": "Clip Martin White polar",
  "1CU-C1B": "Clip Martin Solare Blu Riflettente Polarizzato",
  "1CU-C1BL": "Clip Martin Solare Nero Polarizzato",
  "1CU-C1CN": "Clip Martin Guida Notturna",
  "1CU-C1O": "Clip Martin Solare Arancione Riflettente Polarizzato",
  "1CU-C1P1": "Clip Martin Mogano",
  "1CU-C1P10": "Clip Martin Brunch Vibes",
  "1CU-C1P11": "Clip Martin Sailor",
  "1CU-C1P2": "Clip Martin Zebra",
  "1CU-C1P3": "Clip Martin Hawaii",
  "1CU-C1P4": "Clip Martin Points",
  "1CU-C1P5": "Clip Martin Marmo Blu",
  "1CU-C1P6": "Clip Martin Puzzle",
  "1CU-C1P7": "Clip Martin Garlan",
  "1CU-C1P8": "Clip Martin Valery",
  "1CU-C1P9": "Clip Martin Velvet",
  "1CU-C1PP": "Clip Martin Protezione dallo Schermo",
  "1CU-C2": "Clip Martin Carey",
  "1CU-C3": "Clip Martin Navy",
  "1CU-C4": "Clip Martin Rioja",
  "1CU-C5": "Clip Martin Giallo Limone",
  "1CU-C6": "Clip Martin Rosa Pallido",
  "1CU-C7": "Clip Martin Verde Pistacchio",
  "1CU-C8": "Clip Martin Lilla VeryPery",
  "1CU-C9": "Clip Martin Carey Mar",
  "1TU-C10": "Aste Marpat",
  "1TU-C11": "Aste Senape",
  "1TU-C12": "Aste Iced Coffee",
  "1TU-C13": "Aste Oliver",
  "1TU-C14": "Aste Valentina",
  "1TU-C15": "Aste Red Sunset",
  "1TU-C16": "Aste White Polar",
  "1TU-C1P4": "Aste Red Points",
  "1TU-C2": "Aste Carey",
  "1TU-C3": "Aste Navy",
  "1TU-C4": "Aste Rioja",
  "1TU-C5": "Aste Giallo Limone",
  "1TU-C6": "Aste Rosa Pallido",
  "1TU-C7": "Aste Verde Pistacchio",
  "1TU-C8": "Aste Lilla VeryPery",
  "1TU-C9": "Aste Carey Mar",
  "1TU-P1": "Aste Mogano",
  "1TU-P10": "Aste Brunch Vibes",
  "1TU-P11": "Aste Sailor",
  "1TU-P2": "Aste Zebra",
  "1TU-P3": "Aste Hawaii",
  "1TU-P4": "Aste Points",
  "1TU-P5": "Aste Marmo Blu",
  "1TU-P6": "Aste Puzzle",
  "1TU-P7": "Aste Garlan",
  "1TU-P8": "Aste Valery",
  "1TU-P9": "Aste Velvet",
  "2CU-C1 + 2CU-DA":
    "Clip con base nera Memphis Solar Blue Gradient polarizzata",
  "2CU-C1 + 2CU-DC": "Clip Memphis Solare Azzurro Chiaro Polarizzato",
  "2CU-C1 + 2CU-DF": "Clip Memphis Solare Vino Graduato Polarizzato",
  "2CU-C1 + 2CU-DL": "Clip base nera Memphis Solar Light lilla polarizzata",
  "2CU-C1 + 2CU-DM": "Clip Memphis Solare Marrone Graduato Polarizzato",
  "2CU-C1 + 2CU-EC": "Clip Memphis Solare Rame Riflettente Polarizzato",
  "2CU-C1 + 2CU-EL": "Clip Memphis Solare Viola Riflettente Polarizzato",
  "2CU-C1 + 2CU-EP": "Clip Memphis Solare Specchio Riflettente Polarizzato",
  "2CU-C1 + 2CU-ER": "Clip Memphis Solare Fucsia Riflettente Polarizzato",
  "2CU-C1 + 2CU-EV": "Clip Memphis Solare Verde Riflettente Polarizzato",
  "2CU-C10": "Clip Memphis Marpat",
  "2CU-C11": "Clip Memphis Senape",
  "2CU-C12": "Clip Memphis Iced coffee",
  "2CU-C13": "Clip Memphis Oliver",
  "2CU-C14": "Clip Memphis Valentina",
  "2CU-C15": "Clip Memphis Red Sunset",
  "2CU-C16": "Clip Memphis White Polar",
  "2CU-C1B": "Clip Memphis Solare Nero Polarizzato",
  "2CU-C1BL": "Clip Memphis Solare Nero",
  "2CU-C1CN": "Clip Memphis Guida Notturna",
  "2CU-C1O": "Clip Memphis Solare Arancione Riflettente Polarizzato",
  "2CU-C1P1": "Clip Memphis Mogano",
  "2CU-C1P10": "Clip Memphis Brunch Vibes",
  "2CU-C1P11": "Clip Memphis Sailor",
  "2CU-C1P14": "Clip Memphis Valery",
  "2CU-C1P15": "Clip Memphis Velvet",
  "2CU-C1P2": "Clip Memphis Zebra",
  "2CU-C1P3": "Clip Memphis Hawaii",
  "2CU-C1P4": "Clip Memphis Points",
  "2CU-C1P5": "Clip Memphis Marmo Blu",
  "2CU-C1P6": "Clip Memphis Puzzle",
  "2CU-C1P7": "Clip Memphis Garlan",
  "2CU-C1P8": "Clip Memphis Valery",
  "2CU-C1P9": "Clip Memphis Velvet",
  "2CU-C1PP": "Clip Memphis Protezione dallo Schermo",
  "2CU-C2": "Clip Memphis Carey",
  "2CU-C3": "Clip Memphis Navy",
  "2CU-C4": "Clip Memphis Rioja",
  "2CU-C5": "Clip Memphis Giallo Limone",
  "2CU-C6": "Clip Memphis Rosa Pallido",
  "2CU-C7": "Clip Memphis Verde Pistacchio",
  "2CU-C8": "Clip Memphis Lilla Verypery",
  "2CU-C9": "Clip Memphis Carey Mar",
  accessories_design_title: "Accessori di Design",
  accessories_functional_title: "Accessori Funzionali",
  anti_reflective: "Antiriflesso",
  associated_optics: "Ottica associata",
  basicProgressives: "Progressive Base",
  blue_control: "Blue Control",
  choose_your_convination: "Scegli la tua combinazione:",
  "CICU-01": "Montatura Martin",
  "CICU-02": "Montatura Memphis",
  clips_resume_title: "Clip:",
  cloth: "Panno: Panno in microfibra",
  comment_hint: "<b>Shift ⇧ + Enter ↵</b> per andare a capo",
  comment_optic: "Commento",
  completed_form: "Modulo completato",
  customize: "Personalizza",
  description_clip_functional:
    "Il cliente ha acquistato il PRIMO clip aggiuntivo per 10 euro?",
  design: "Design",
  dont_send_btn: "Non inviare",
  eliteProgressives: "Progressive Elite",
  error_num_min:
    "Inserisci un numero maggiore o uguale a quello calcolato sulla base dei prodotti inseriti",
  finalPage: "Pagina Finale",
  flipo_client: "Cliente FLiPO",
  frame_resume_title: "Montatura:",
  frame_title: "Montatura",
  functional: "Funzionale",
  go_to: "Avanti",
  gretting: "Ciao",
  gretting_subtitle: "Modulo dell'ordine per",
  invoice_resume_title: "Fattura",
  invoicedToTheCustomer: "Fatturato al Cliente",
  lenses_type_resume_title: "Tipo di lente:",
  mediumProgressives: "Progressive Media",
  monofocalManufacture: "Monofocali Produzione",
  monofocalorProgressive: "Monofocali o Progressive",
  monofocalStock: "Monofocale Stock",
  no: "No",
  not_go_to: "Non proseguire",
  pack_curioso: "Pachetto Curioso",
  pack_flipante: "Pacchetto Meraviglioso",
  pack_flipante_no_caja: "Meraviglioso (Senza scatola)",
  pack_full: "Pacchetto Full",
  pack_title: "Pacchetti",
  packs_resume_title: "Pacchetto:",
  placeholder_text: "Scrivi la tua risposta qui",
  pouch: "Astuccio: Custodia dei clip",
  press_enter: "premi <b>Enter ↵</b>",
  progressiveTop: "Progressive Top",
  reduction_resume_title: "Riduzione:",
  resume: "Sommario",
  review: "Revisione",
  sale_stock: "Vendita Stock",
  sending: "Invio...",
  sheath: "Custodia",
  sold_data: "Dati di vendita",
  standard_clip: "Clip Standard",
  start: "Inizia",
  sumbit: "Invia",
  talc_of: "Talco di:",
  temples: "Aste",
  temples_resume_title: "Aste:",
  temples_title: "Aste",
  there_was_a_problem: "C'è stato un problema",
  title_final_form:
    "Ora hai concluso il modulo della montatura e degli accessori! \n\n! Ricorda che se è FLiPO che produce le lenti, il modulo delle lenti è ancora in sospeso.",
  title_insert_data_customer: "Inserisci i dati del cliente",
  title_isFLiPO: "La montatura venduta era FLiPO?",
  titleFileBlock: "Carica il file excel della gradazione",
  type_of_treatment: "Che tipo di trattamento?",
  will_FLiPO_make_lenses: "Chi si occuperà delle lenti?",
  yes: "Sì",
  total_value: "Valore totale",
  comment_payment:
    "Qualsiasi dettaglio che non sia stato considerato nelle domande precedenti, o se il cliente ha scelto di aggiungere prodotti, puoi specificarlo qui\n\t- Clip Funzionali: 25€\n\t- Clip di Design: 20€\n\t- Aste: 20€",
  out_of_stock: "Esaurito",
  has_financing: "Il cliente ha richiesto il finanziamento?",
  financing: "Finanziamento",
  yes_formPage: "Sì",
  no_formPage: "No",

  _comment_5: "global",
  spain: "Spagna",
  portugal: "Portogallo",
  england: "Inghilterra",
  copyright: "Tutti i diritti riservati",
  address: "Indirizzo",
  active: "Attivo",
  inactive: "Inattivo",
  back_dashboard: "Torna all'inizio",
  status_todo: "Da fare",
  status_to_pay: "Da Pagare",
  status_not_assist: "Appuntamento mancato",
  status_assist: "Appuntamento avvenuto",
  status_notify_not_assist: "Cancellato dal cliente",
  status_paid: "Pagata",
  status_wrong_team: "Errore interno",
  status_not_buy: "Non acquistato",
  status_optician_rescheduled: "Riprogrammata dall'Ottico",
  status_sell_stock: "Vendita Stock",
  back_to: "Torna a",
  back: "Indietro",
  optic: "Ottica",
  for_see: "Per vedere...",

  _comment_6: "homePage",
  italy: "Italia",
  appointments: "Appuntamenti",
  conversion: "Tasso di Conversione",
  globalStats: "Statistiche globali",
  lastMonth: "Ultimi 30 giorni",
  opticName: "Nome Ottica",
  opticSearch: "Cerca Ottica",
  sales: "Vendite",

  _comment_7: "lensesFormPage",
  addendum: "Addizione",
  aisle: "Canale di progressione",
  axis: "Asse",
  base: "Base",
  corto: "Corto",
  cylinder: "Cilindro",
  gretting_lenses: "Modulo per ordinare le lenti dell'ordine'",
  info_esc_form_lenses_1: "Ricordatelo quando premi il tasto",
  info_esc_form_lenses_2: "puoi vedere il riepilogo del modulo",
  largo: "Lungo",
  left_eye_graduation_title_1: "Occhio Sinistro",
  left_eye_offset: "Decentramento Occhio Sinistro (mm)",
  maximum_distance: "Distanza Massima (cm)",
  medio: "Medio",
  mounting_dimensions: "Dimensioni di Montaggio",
  od_DNP: "DP Occhio Destro",
  od_height: "Altezza Occhio Destro",
  oi_DNP: "DP Occhio Sinistro",
  oi_height: "Altezza Occhio Sinistro",
  prism_axis: "Asse Prisma",
  prism_value: "Valore Prisma",
  progressive_top_range: "Progressiva Gamma Top",
  right_eye_graduation_title_1: "Occhio Destro",
  right_eye_offset: "Decentramento Occhio Destro (mm)",
  size: "Dimensione",
  sphere: "Sfero",

  _comment_8: "loginPage",
  checkCredentials: "Credenziali non valide",
  invalidCredentials: "Credenziali non valide. Verificale.",
  loginButton: "Accedi",
  loginWelcome: "Benvenut@!",
  typeCredentials: "Inserisci le tue credenziali",
  yourPassword: "La tua password",
  yourUsername: "Il tuo utente",

  _comment_9: "odooStates",
  basics: "Basics",
  choose_reason: "Escolha um motivo",
  docs: "Documentação",
  models: "Modelos",
  my_optics: "Minha Optica",
  next_time: "Próxima vez",
  other: "Outros",
  pricing: "Preços",
  product: "Produto",
  reason: "Motivo",
  state_order_assigned: "Annullato",
  state_order_cancel: "Annullato",
  state_order_confirmed: "Annullato",
  state_order_done: "Annullato",
  state_order_draft: "Annullato",
  state_order_for_prepare: "Prodotto da preparare",
  state_order_prepared: "Prodotto preparato - In attesa di lenti",
  state_order_preparing: "Prodotto in preparazione'",
  state_order_sended: "Prodotto inviato",
  state_order_total_prepared: "Ordine preparato",
  state_order_waiting: "In attesa di un'altra operazione",

  _comment_10: "opticPage",
  "<25": "Minore di 25",
  ">45": "Maggiore di 45",
  "25<X<45": "Tra i 25 e i 45",
  admin_users_active: "Attivo",
  admin_users_create: "Crea Utente",
  admin_users_delete_confirm: "Vuoi eliminare questo utente?",
  admin_users_edit: "Modifica utente",
  admin_users_name: "Nome",
  admin_users_optics: "Ottiche",
  admin_users_optics_select: "Seleziona la tua/le tue ottiche",
  admin_users_optics_suggested: "Ottica suggerita",
  admin_users_password: "Password",
  admin_users_phone: "Telefono",
  admin_users_roles: "Ruoli",
  admin_users_roles_select: "Seleziona il ruolo",
  admin_users_username: "Nome utente",
  admin_zone: "Area Admin",
  age: "Età",
  agenda: "Agenda",
  analytics: "Analitica",
  appointment_comment: "Commenti relativi all’appuntamento",
  appointments_filter: "Filtra appuntamenti per Stato:",
  appointments_filter_info:
    "Puoi filtrare gli appuntamenti per stato e creare blocchi di tempo per bloccare",
  appointments_states: "Stati degli Appuntamenti",
  change_status_wrong: "Cambia stato nel caso ti sia sbagliato/a",
  client_from: "Cliente di",
  comment_appointment: "Appuntamento commentato.",
  comment_appointment_any: "L'appuntamento è stato commentato.",
  "commenting_appointment_of ": "Commentando l'appuntamento di:",
  conversion_graph: "Grafico di Conversione degli Appuntamenti",
  conversion_graph_converted: "Convertite",
  conversion_graph_failed: "Fallite",
  conversion_graph_rate_short: "Conversione",
  conversion_graph_total: "Totale",
  conversion_graph_unit: "Tasso di Conversione",
  country: "Paese",
  create_appointment: "Crea Appuntamento",
  create_block: "Crea Blocco Orario",
  create_block_full: "È per l'intera giornata?",
  create_customer: "Creare cliente",
  created_appointment: "Appuntamento creato",
  created_user: "Utente creato",
  customer_code: "Codice cliente",
  customer_created: "Cliente creato",
  customerSearch: "Cerca Clienti",
  dashboard: "Inizio",
  data_not_buy: "Menziona il Mancato Acquisto",
  day: "Giorno",
  delete: "Elimina",
  delete_block: "Vuoi eliminare questo blocco?",
  edit: "Modifica",
  editing_appointment_of: "Modificando Appuntamento di:",
  email: "Email",
  end_date: "Termina il",
  fill_form: "Completare",
  fill_form_lenses_now: "Vuoi compilare subito il modulo per le lenti?",
  fill_now: "Compila adesso",
  form_create_block_full: "È per tutto il giorno?",
  form_end_date: "Finisce il",
  form_filter: "Filtra",
  form_for_fill: "Modulo da compilare",
  form_lenses_for_fill: "Modulo per le lenti da compilare",
  form_reset: "Reimposta",
  form_sell_stock: "Modulo Vendite Stock",
  form_start_date: "Inizia il",
  get_support: "Ottieni aiuto tramite WhatsApp",
  has_assisted: "Si sono presentati.",
  has_bought: "Ha acquistato",
  has_not_assisted: "Non si sono presentati .",
  has_not_bought: "Non ha acquistato",
  has_not_payed: "Non ha pagato",
  has_payed: "Ha pagato.",
  home: "Home",
  information: "Informazioni",
  is_assisted: "Si sono presentati?",
  is_buy: "Hanno acquistato?",
  is_flipo_client: "Sei un cliente Flipo?",
  later: "Più tardi",
  lenses_type_select: "Gradazione personalizzata",
  logout: "Uscire",
  maps: "Guarda su Maps",
  modified_user: "Utente modificato",
  month: "Mese",
  next: "Prossimo",
  no_spaces: "Non possono esserci spazi",
  notFound: "Non trovato",
  num_appointment: "Num. Appuntamento",
  num_order: "Num. Ordine",
  optic_history: "Ottiche Visitate",
  optic_history_action: "Mostrare",
  payments: "Pagamenti",
  pending_form: "Appuntamenti con modulo pendente",
  pending_lenses_form: "Modulo lenti in sospeso",
  phone_number: "Numero di telefono",
  post_code: "Codice postale",
  prev: "Precedente",
  privacy: "Politica sulla Privacy",
  reason_for_not_purchasing: "Motivo del mancato acquisto",
  remember_fill_lenses_form: "Ricorda di compilare il modulo per le lenti",
  required: "Obbligatorio",
  restore_appointment: "Clicca per modificare l'Appuntamento.",
  restore_appointment_todo:
    "L'appuntamento è stato contrassegnato come in sospeso.",
  save: "Salvare",
  select_age: "Seleziona l'età",
  select_customer: "Seleziona il cliente",
  start_date: "Inizia il",
  state: "Stato",
  there_can_be_no_gaps: "Non possono esserci spazi",
  this_month: "Questo mese",
  this_week: "Questa settimana",
  title_modal_remember_fill_form:
    "Ricorda di compilare i moduli che hai in sospeso!",
  today: "Oggi",
  total_appointments: "Appuntamenti Totali",
  unsold_appointment_panel_toggle: "Commenti",
  unsold_appointment_panel_toggle_error:
    "Puoi utilizzare questa funzione solo se l'appuntamento non ha portato a una vendita.",
  unsold_appointment_panel_toggle_info:
    "Compila le informazioni su questo appuntamento che non ha portato a una vendita.",
  update_appointment: "Appuntamento Aggiornato.",
  update_appointment_any: "L'appuntamento è stato aggiornato.",
  update_appointment_canceled: "L'appuntamento è stato cancellato.",
  update_appointment_confirmed: "L'appuntamento è stato confermato.",
  update_appointment_error: "Questo appuntamento non è più modificabile.",
  update_appointment_not_buy:
    "L'appuntamento è stato contrassegnato come Mancato acquisto.",
  update_appointment_payed:
    "L'appuntamento è stato contrassegnato come Pagato.",
  updatedLang: "Hai aggiornato la lingua dell'ERP.",
  updatedLangTo: "Lingua cambiata in",
  user_already_exists: "L'utente esiste già",
  user_last_name: "Cognome",
  user_list: "Lista degli Utenti",
  view_orders: "Vedi ordini",
  week: "Settimana",
  without_info_graduation: "Senza informazioni sulla gradazione",
  workWeek: "Settimana Lavorativa",
  form_title: "Titolo del blocco (opzionale)",
  gama_basica: "Livello Base",
  gama_media: "Livello Medio",
  gama_elite: "Livello Elite",
  gama_top: "Livello Superiore",
  blocked: "Bloccato",
  title_must_not_be_empty: "Il titolo non deve essere vuoto",

  _comment_11: "paymentPage",
  accessories: "Accessori",
  accessory: "Accessorio",
  advanced_filters: "Filtri avanzati",
  all_elems: "Tutti",
  antireflective: "Antiriflesso",
  appointment: "Appuntamento",
  appointment_date: "Data dell'appuntamento",
  are_you_want_fill_lenses_form: "Vuoi compilare il modulo delle lenti?",
  at: "alle",
  back_orders: "Torna agli Ordini",
  behindhand: "In ritardo",
  billed: "Fatturato",
  called: "Chiamato",
  canceled: "Annullato",
  card: "Carta",
  cash: "Contanti",
  category_monofocales: "Monofocale",
  category_progresivas: "Progressiva",
  choose_property: "Scegli una proprietà",
  choose_value: "Scegli un valore",
  clear_all: "Cancella tutto",
  close_distance: "Distanza di chiusura",
  coming_soon: "Disponibile a breve",
  comment: "Commento",
  comment_of_optic: "Commento dell'Ottico",
  confirmed: "Confermato",
  created_on: "Creato il",
  cuppon: "Coupon",
  date: "Data",
  date_form: "Data Modulo",
  date_order: "Data Ordine",
  decenter: "Decentramento",
  degree: "Grado",
  delivered_customer: "onsegnato al cliente",
  delivered_local: "Consegnato in loco",
  details: "Dettagli",
  error: "Errore",
  eyes: "Occhi",
  eyes_form_not_filled: "Modulo occhi non ancora compilato",
  form_of: "Forma di",
  graduation: "Gradazione",
  hall: "Sala",
  in_preparation: "In preparazione",
  last_30_days: "Ultimi 30 giorni",
  last_elems: "Ultimi",
  left: "Sinistra",
  lens_form: "Modulo lenti",
  lens_order: "Ordine lente",
  lens_provider: "Fornitore lenti",
  lense: "Lente",
  lense_form_with_id: "Modulo con ID",
  lense_order_with_id: "Ordine lente con ID",
  lenses: "Lenti",
  lenses_type: "Tipo di lenti",
  lost: "Perso",
  monofocales: "monofocali",
  more_late: "Più tardi",
  mount: "Modello",
  my_last_orders: "I miei ultimi ordini",
  name: "Nome",
  new_order: "Nuovo ordine",
  no_comment: "Senza commento",
  none: "Nessuno",
  not_available: "Non disponibile",
  not_filled_yet: "Ancora non compilato",
  not_graduated: "Non graduato",
  optic_added: "Ottica aggiunta",
  optic_select: "Seleziona la tua ottica",
  order: "Ordine",
  order_num: "Num. DDT",
  order_of: "Ordine di",
  order_status: "Stato dell'ordine",
  ordered_lenses: "Lenti ordinate",
  paid: "Pagato",
  paid_with: "Pagato con",
  payment_page: "Pagina di Pagamento",
  payments_record: "Pagamenti registrati",
  pending: "In attesa",
  pending_payment: "Pagamento pendente",
  progresivas: "progressive",
  phone: "Telefono",
  price: "Prezzo",
  processed: "Processato",
  property: "Proprietà",
  received: "Ricevuto",
  recent_payments: "Pagamenti recenti",
  reduction: "Riduzione",
  refund_accepted: "Rimborso accettato",
  refund_rejected: "Rimborso rifiutato",
  refund_requested: "Rimborso richiesto",
  right: "Destra",
  search: "Cerca",
  search_by: "Cerca per",
  search_optics: "Cerca ottica",
  select_date: "Seleziona data",
  select_optic: "Seleziona un'ottica",
  seller: "Venditore",
  sent: "Inviato",
  showing: "Mostrando",
  status: "Stato",
  status_online: "Pagato online",
  status_optical_error: "Fallito dall'Ottica",
  status_optical_rescheduling: "Riprogrammato dall'Ottica",
  status_unknown: "Sconosciuto",
  talc: "Talco",
  total_paid: "Totale pagato",
  total_spent: "Totale speso",
  treatment: "Trattamento",
  type_word: "Tipo",
  value: "Valore",
  view_optic: "Vedi Ottica",
  view_order: "Vedi ordine",
  watchlist_added: "ora è nella tua lista di monitoraggio,",
  watchlist_cleared_desc: "La lista di monitoraggio è stata cancellata",
  watchlist_cleared_title: "Lista di monitoraggio pulita",
  without_frame: "Senza montatura",

  _comment_12: "paymentPage",
  add: "Aggiungi",
  add_device: "Aggiungi nuovo dispositivo",
  amount: "Importo",
  amount_to_pay: "Importo da pagare",
  available_tpv: "POS disponibili",
  choose_payment_type: "Scegli il tipo di pagamento",
  complementary: "Pagamento del saldo,",
  confirm: "CONFERMA",
  confirmation: "Conferma",
  could_not_be_connected: "Impossibile connettersi al dispositivo",
  deposit: "Acconto",
  deposit_greater_than: "L'acconto deve essere superiore a",
  device_version: "Versione del dispositivo",
  enter_key: "Inserisci la chiave",
  failed_attempt: "Tentativo fallito",
  full: "Pagamento Completo",
  n_serial: "Numero di serie",
  order_details: "Dettagli dell'ordine",
  payment_greater_than: "Il pagamento deve essere uguale o superiore a",
  payment_type: "Tipo di pagamento",
  perfect: "Perfetto",
  recommendations: "RACCOMANDAZIONI",
  remaining_to_be_paid: "Rimane da pagare",
  remember_that:
    "il cliente dovrà pagare quando passerà a ritirare il suo ordine.",
  review_tpv: "Controlla il tuo POS per effettuare il pagamento",
  start_payment: "Inizia pagamento",
  terminal_connected: "Terminale connesso",
  title_remember_that: "Ricorda che",
  transfer_failed: "Trasferimento fallito!",
  call_issuer: "La carta è stata rifiutata per un motivo sconosciuto.",
  offline_pin_required: "La carta è stata rifiutata perché richiede un PIN",
  online_or_offline_pin_required:
    "La carta è stata rifiutata perché richiede un PIN",
  generic_decline: "La tua carta è stata declinata",
  incorrect_pin: "Il PIN inserito non è corretto",
  withdrawal_count_limit_exceeded:
    "Il cliente ha superato il saldo o il limite di credito disponibile sulla sua carta",
  pin_try_exceeded: "È stato superato il numero consentito di tentativi PIN",
  try_again: "Prova di nuovo",
  with_card: "Con carta",
  with_cash: "In contanti",
  you_will_pay: "Pagherai",
  transfer_success: "Trasferimento completato con successo",
  success: "Successo",
  billing: "Fatturazione",
  block_by_country: "Blocca per Paese",
  orders: "Ordini",
  transactions: "Transazioni",
  billings: "Fatturazioni",

  _comment_13: "tpvInstructions",
  instructions1: "ASSICURATI CHE IL TERMINALE ABBIA LA BATTERIA CARICA.",
  instructions2: "ACCENDI IL DISPOSITIVO.",
  instructions3:
    "VAI ALLA CONFIGURAZIONE DEL TERMINALE, PER FARLO DEVI SCORRERE\n IL DITO DAL BORDO SINISTRO DELLO SCHERMO VERSO IL DESTRO,\n SI APRIRÀ UN PANNELLO.\n",
  instructions4:
    'POI, SELEZIONA CONFIGURAZIONE E INSERISCI IL\n SEGUENTE PIN: 07139. APPARIRANNO DIVERSE OPZIONI. SELEZIONA\n ""RETE"" E CONNETTITI AL TUO WI-FI.\n',
  instructions5:
    'UNA VOLTA CONNESSO AL WI-FI, TORNA AL MENU PRECEDENTE E SELEZIONA L\'OPZIONE ""GENERA UN CODICE DI ABBINAMENTO"". VERRÀ GENERATA UNA CHIAVE CHE DOVRAI INSERIRE NELL\'APPLICAZIONE.',
  instructions6:
    'IL POSTO PER INSERIRE QUESTO CODICE SI TROVA NELLA FINESTRA SEGUENTE DEL MODULO ""AGGIUNGI NUOVO DISPOSITIVO"". UNA VOLTA INSERITO E CONNESSO CORRETTAMENTE APPARIRÀ IN ""POS DISPONIBILI"".',
  instructions7: "SELEZIONA IL POS ED EFFETTUA IL PAGAMENTO.",
  instructions8:
    "IN QUESTO MODO IL POS È ACCOPPIATO E ASSOCIATO ALLA TUA OTTICA. PER LE OPERAZIONI SUCCESSIVE SARÀ SUFFICIENTE CONNETTERLO ALLA TUA RETE WI-FI.",

  _comment_14: "userListPage",
  form_age: "Età",
  form_email: "Email",
  form_is_flipo_client: "È cliente Flipo?",
  form_last_name: "Cognome",
  form_post_code: "Codice Postale",
  form_select_age: "Seleziona età",
  form_users_name: "Nome",
  form_users_phone: "Telefono",
  user_exists: "Il cliente esiste",
  user_not_exists: "Non esiste nessun cliente con quel numero di telefono",

  _comment_15: "wizard",
  wizard_reminder_1: "Ricorda che premendo il tasto",
  wizard_ESC: "ESC",
  wizard_reminder_3: "puoi vedere il sommario dei passi",
  wizard_reminder_4: "clips",
  wizard_reminder_5: "e",
  wizard_reminder_6: "pacchetti",
  wizard_reminder_7: "che hai",
  wizard_reminder_8: "selezionato.",

  _comment_16: "ORDER SYSTEM - SISTEMA DE PEDIDOS",

  _comment_17: "CardOrdersSettings cos",
  cos_list_tab_1: "Selezionare i prodotti",
  cos_list_tab_2: "Scegliere le opzioni",
  cos_list_tab_3: "Sintesi e promozioni",

  _comment_18: "CardOrderItemsContent coic",
  coic_title_1: "Per favore aggiungi i prodotti da ordinare:",
  coic_title_2:
    "Qui potrai aggiungere i prodotti per completare il tuo ordine a FLiPO",
  coic_description_1: "I soliti pacchetti: curioso, Full, Flipante",
  coic_description_2:
    "Acquista accessori singolarmente, non associati ai pacchetti",

  _comment_19: "CardproductTitle",
  c_title_pack: "Pacchetti",
  c_title_accessories: "Accessori Individuali",
  c_title_notFLIPO: "Vendita Non FLiPO",

  _comment_20: "CardproductDesc",
  c_desc_pack: "I soliti pacchetti: curioso, Full, Flipante",
  c_desc_accessories:
    "Acquista accessori singolarmente, non associati ai pacchetti",
  c_desc_notFLIPO: "Registra qui le vendite che non sono di prodotti FLiPO.",

  _comment_21: "OrderSystem component",
  c_customer_info_title: "Informazioni sull’appuntamento:",
  c_order_resume_title: "Riepilogo dei prodotti in questo ordine",
  b_order_resume_title: "Aggiungi più prodotti",
  b_order_resume_continue_title1: "CONTINUA",
  b_order_resume_continue_title2: "PRONTO PER PAGARE",
  c_promotions_title: "Promozioni applicabili per questo appuntamento:",
  c_title_order_list: "Il tuo Ordine",
  b_title_order_list: "CONTINUA",
  c_accessories_order_list_title1: "Accessori",
  c_accessories_order_list_title2: "Accessori Extra",
  c_order_item_title: "Seleziona un prodotto per iniziare",
  c_order_item_subtitle: "Personalizza i prodotti da inviare nell’ordine:",
  c_pack_details_title: "Questo Pack include:",
  list_flipante: "Pachetto Meraviglioso",
  list_full: "Pachetto FULL",
  list_curioso: "Pachetto Curioso",
  m_title_pack_additional: "(Clip aggiuntiva 10 €)",
  list_temples: "Aste",
  list_functional: "Clips Funzionali",
  list_packaging: "Custodie",
  list_design: "Clips di Design",
  repairation: "Riparazione",
  list_functional_design: "Clip Funzionale di Design",
  m_not_flipo: "Non Disponibile per Tipo Vendita Stock",
  b_not_flipo: "CONTINUA",
  c_type_lens_exist:
    "Questa sezione non può essere modificata in un ordine esistente.",
  c_form_lens_title: "Modulo lenti",
  c_from_lens_q1: "Chi si occuperà delle lenti?",
  c_from_lens_q2: "Tipo di Lente",
  c_from_lens_q3: "Trattamento",
  c_from_lens_q4: "Riduzione del Trattamento",
  c_lens_options1: "Monofocale Stock",
  c_lens_options2: "Monofocali Produzione",
  c_lens_options3: "Monofocale di supporto",
  c_lens_options4: "Progressive Base",
  c_lens_options5: "Progressive Medio",
  c_lens_options6: "Progressive Elite",
  c_lens_options7: "Progressive Top",
  c_lens_options8: "Occupazionali",
  c_lens_seller_option1: "Ottico associato",
  c_lens_seller_option2: "FLiPO",
  c_lens_seller_option3: "Nessuno",
  c_anti_reflective: "Antiriflesso",
  c_anti_reflective_plus: "Antiriflesso Plus",
  c_blue_control: "Controllo Blu",
  c_promotions_step1: "Promozioni applicate",
  c_promotions_step2: "Promozioni applicabili",
  c_lens_type_advice1: "Nessun pacchetto",
  b_resume_status_product: "Completo",
  b_resume_status_product2: "Incompleto",
  b_resume_status_product3: "Obbligatorio",
  b_status_product: "Completato",
  b_status_product2: "Incompleto",
  b_status_product3: "Obbligatorio",
  s_m_title1: "Una (1) clip funzionale",
  s_m_title2: "clip funzionali",
  s_m_title3: "o una (1) clip di design",
  s_m_title4: "o",
  s_m_title5: "o",
  s_m_title6: "clip di design (a scelta) + aste coordinate",
  s_m_title7: "Un (1) set di aste",
  m_number_1: "Uno (1)",
  m_number_2: "Due (2)",
  m_number_3: "Tre (3)",
  m_number_4: "Quattro (4)",
  m_number_5: "Cinque (5)",
  m_number_6: "Sei (6)",
  m_number_7: "Sette (7)",
  m_number_8: "Otto (8)",
  m_number_9: "Nove (9)",
  m_number_10: "Dieci (10)",
  m_number_11: "Undici (11)",
  m_number_12: "Dodici (12)",
  m_number_13: "Tredici (13)",
  m_number_14: "Quattordici (14)",
  m_number_15: "Quindici (15)",
  m_number_16: "Sedici (16)",
  m_number_17: "Diciassette (17)",
  m_number_18: "Diciotto (18)",
  m_number_19: "Diciannove (19)",
  m_number_20: "Venti (20)",
  m_menu_type_lens: "Tipo di Lenti",
  m_menu_type_frame: "Tipo di Montatura",
  m_menu_type_functional: "Accessorio Funzionale",
  m_menu_type_design: "Clip di Design",
  m_menu_type_temples: "Aste",
  m_menu_type_packaging: "Confezione",
  i_h_cupon: "Codice sconto o carta regalo",
  b_application_promotion: "Applica",
  b_delete_promotion: "Elimina",
  b_add_promotion: "Applica",
  m_title_list: "LISTA ORDINE",
  sm_title_list: "Cliente",
  m_column_billing_list: "PRODOTTO",
  m_column_billing_list2: "QUANTITÀ",
  m_column_billing_list3: "Totale",
  m_title_aditional: "Accessori aggiuntivi (promozioni)",
  m_title_subtotal: "Subtotale",
  m_title_disc: "Sconto",
  b_title_back_list: "Configura",
  b_title_back_list2: "Configura Ordine",
  b_title_back_list3: "Continua",
  b_title_back_list4: "CONTINUA",
  m_title_selection: "La tua selezione",
  m_title_pack_selection: "Pacchetto selezionato",
  m_title_pack_selection2: "Tipo di pacchetto:",
  m_title_selection2: "Montatura:",
  m_title_selection3: "Non ancora selezionato",
  m_title_selection4: "Prezzo:",
  m_title_selection5: "Tipo di lenti",
  m_title_selection6: "Non configurato",
  m_title_selection7: "Trattamento:",
  m_title_selection8: "Non specificato:",
  m_title_selection9: "Riduzione del trattamento:",
  m_title_selection10: "Non si applica",
  m_title_selection11: "Accessori del Pacchetto",
  m_title_selection12: "Nota:",
  m_title_selection13:
    "Di seguito sono mostrati solo gli accessori configurati per questo pacchetto.",
  m_title_selection14: "SKU:",
  m_title_selection15_accesory: "Accessorio:",
  m_title_selection17: "Trattamento:",
  m_title_selection18: "Riduzione:",
  m_resume_submit_title: "Riepilogo ordine",
  m_payment_title: "Scegli un metodo di pagamento",
  c_payment_type_title: "POS FLiPO",
  c_payment_type_subtitle: "pagamento tramite il nostro POS'",
  c_payment_type_subtitle2: "pagamento in contanti",
  c_payment_type_subtitle3: "CONTANTI",
  c_payment_type_subtitle4: "pagamento tramite il nostro POS'",
  c_paymenet_input: "PAGAMENTO IN CONTANTI",
  c_paymenet_input2: "TOTALE DA PAGARE DOJO",
  c_amount_currency: "Valuta",
  c_process_payment: "Stiamo elaborando il tuo pagamento",
  m_title_selection19: "Tipo:",
  m_title_completed_selection20:
    "Il pacchetto è completamente configurato e pronto.",
  m_title_completed_selection21:
    "Il pacchetto non è ancora completamente configurato.",
  m_title_completed_selection22: "Accessori aggiuntivi",
  m_title_completed_selection23: "Accessori selezionati",
  m_title_selection24: "Promozione:",
  m_title_selection25: "Montatura:",
  m_title_selection26: "Nessuna montatura selezionata",
  m_title_selection27: "Importante:",
  m_title_selection28:
    "Una volta confermato questo ordine, non potrà essere modificato. L'ordine sarà creato e elaborato immediatamente.",
  m_title_selection29: "Prezzo totale:",
  m_title_selection30: "Conferma ordine",
  m_title_selection31: "Annulla",
  m_title_selection32: "Conferma",
  m_type_no_frame: "Per favore seleziona un tipo di montatura",

  _comment_22: "new form eye",
  c_form_eye_title: "Modulo degli Occhi",
  m_form_eye: "Sfera",
  m_form_eye2: "Cilindro",
  m_form_eye3: "Asse",
  m_form_eye4: "Aggiunta",
  m_form_eye5: "Asse del Prisma",
  m_form_eye6: "Valore del Prisma",
  m_form_eye7: "Centratura Montatura/Cliente",
  m_form_eye8: "CORRIDOI DISPONIBILI PER GAMMA PROGRESSIVA",
  m_form_eye9: "Corridoio",
  m_form_eye10: "Corto",
  m_form_eye11: "Lungo",
  m_form_eye12: "DATI AGGIUNTIVI PER GAMMA PROGRESSIVA TOP (OPZIONALE)",
  m_form_eye13: "Invia",
  m_form_eye14: "DNP",
  m_form_eye15: "Altezza",
  m_form_eye16: "Senza prisma",
  m_form_eye17: "Valore del Prisma",
  m_form_eye18: "Decentramento",
  m_form_eye19: "Distanza Massima (cm)",
  m_form_eye20: "Commenti aggiuntivi sulla prescrizione",
  m_form_eye21: "Dettagli della Prescrizione",
  m_form_eye22: "Bolla di Consegna:",
  m_form_eye23: "Sfera:",
  m_form_eye24: "Asse del Prisma:",
  m_form_eye25: "Valore dell’Asse:",
  m_form_eye26: "Corridoio: Corto",
  m_form_eye27: "Corridoio: Lungo",
  REMINDER_TITLE: "RICORDA CHE",
  REMINDER_MESSAGE:
    "Abbiamo bisogno che tu compili il modulo di gradazione delle lenti per poter preparare il tuo ordine. Vorresti farlo ora?",
  YES_BUTTON: "SÌ",
  NO_BUTTON: "NO",
  m_form_eye_title: "Modulo di richiesta lenti:",
  m_acdemy_title: "Tutorial ERP Academy",
  m_acdemy_subtitle: "Tutorial FLiPO",
  m_acdemy_title_card1: "Tutorial Softr per Principianti",
  m_acdemy_desc_card2:
    "Softr è uno dei principali strumenti per costruire applicazioni e portali interni per la tua azienda o organizzazione utilizzando i tuoi dati provenienti da Airtable, Google Sheets, SmartSuite e altre fonti di dati popolari.",
  m_acdemy_title_card2: "Tabelle Google Sheets",
  m_error_stock_title: "Spiacente",
  m_error_stock_subtitle: "Stiamo riscontrando dei problemi, riprova più tardi",
  m_new_table_order_s1: "Numero Ordine",
  m_new_table_order_s2: "Nome Cliente",
  m_new_table_order_s3: "Rimuovi Filtri",
  m_new_table_order_c1: "Nº. Documento",
  m_new_table_order_c2: "Cliente",
  m_new_table_order_c3: "Creazione",
  m_new_table_order_c4: "Ultimo Pagamento",
  m_new_table_order_c5: "Pagato",
  m_new_table_order_c6: "Prezzo Totale",
  m_new_table_order_c7: "Gradazione",
  m_new_table_order_c8: "Ordine",
  m_new_table_order_c9: "Pagamento",
  m_new_payment_dojo_1: "Tempo rimanente: ",
  m_new_payment_dojo_2: "secondi",
  m_new_payment_dojo_3: "È LA FIRMA CORRETTA?",
  m_new_payment_dojo_4: "RIFIUTATO",
  m_new_payment_dojo_5: "INSERIMENTO PIN",
  m_new_payment_dojo_6:
    "Abbiamo problemi a elaborare la risposta del pagamento.",
  m_new_payment_dojo_7:
    "Errore di comunicazione con il terminale. Si prega di verificare se la transazione è stata completata. SI PREGA DI CONTATTARE IL VOSTRO GESTORE FLIPO",
  m_new_payment_dojo_8: "CONTINUA",
  m_new_payment_dojo_9: "TPV non disponibile",
  m_new_payment_dojo_10:
    "Riprova tra 10 secondi o controlla lo schermo e i cavi del terminale. Se il problema persiste, contatta il supporto.",
  m_new_payment_dojo_11: "Errore di connessione con il terminale",
  m_new_payment_dojo_12: "Il pagamento è stato registrato correttamente?",
  m_new_payment_dojo_13: "STIAMO INIZIANDO IL PAGAMENTO",
  CALENDAR: "CALENDARIO",
  ORDERS: "ORDINI",
  APPOINTMENT: "APPUNTAMENTO",
  t_clip_additional: "Accessorio aggiuntivo",
  modal_additional_accessory_title: "Accessorio aggiuntivo",
  modal_additional_accessory_question:
    "Vuoi aggiungere un accessorio aggiuntivo al pack per 10 euro?",
  modal_additional_accessory_description:
    "Migliora il tuo pack aggiungendo un accessorio aggiuntivo per soli 10 euro.",
  product_list_packs_new_frames: "Nuova collezione",
  product_list_packs_old_frames: "Martin e Memphis",
  tour_b_1: "Prec",
  tour_b_2: "Succ",
  tour_c_title_1: "Progresso del tuo Ordine",
  tour_c_subtitle_1:
    "Questo intestazione mostra come procede il tuo ordine. Ci sono tre passaggi totali da completare.",
  tour_c_title_2: "Lista dei Pacchetti",
  tour_c_subtitle_2:
    "Questa sezione mostra un elenco di carte prodotto nella categoria",
  tour_c_subtitle_2_2: "Pacchetti",
  tour_c_subtitle_2_3:
    ". Puoi fare clic sulla carta Pacchetti per maggiori dettagli.",
  tour_c_title_3: "Vendita 'NON FLIPO'",
  tour_c_subtitle_3:
    "Questa sezione è dedicata esclusivamente alla registrazione di vendite che non appartengono a",
  tour_c_subtitle_3_1: "FLIPO",
  tour_c_subtitle_3_2:
    ". Si prega di utilizzare quest'area per vendite non correlate ai nostri prodotti standard.",
  product_cards_accessories_title: "Elenco degli Accessori",
  product_cards_accessories_subtitle_1:
    "Questa sezione mostra un elenco di carte prodotto nella categoria",
  product_cards_accessories_highlight: "Accessori",
  product_cards_accessories_subtitle_2:
    "Puoi fare clic sulla carta dei Pacchetti per maggiori dettagli.",
  product_list_title: "Elenco dei Prodotti Selezionati",
  product_list_subtitle_1:
    "Questa carta mostra un elenco di prodotti in cui gli articoli selezionati dalle categorie",
  product_list_highlight_1: "Accessori",
  product_list_highlight_2: "Pacchetti",
  product_list_subtitle_2: " si rifletteranno qui.",
  product_list_actions:
    "Sarai in grado di: Eliminare, Aggiungere e visualizzare la quantità di ciascuno.",
  continue_button_title: 'Pulsante "Continua"',
  continue_button_subtitle:
    'Il pulsante "Continua" si attiverà una volta che avrai aggiunto qualcosa al tuo ordine. Puoi usare questo pulsante per passare al passaggio successivo dell’ordine e proseguire con l’acquisto.',
  order_summary_title: "Riepilogo del tuo ordine",
  order_summary_subtitle_1:
    "Questa carta mostra un riepilogo del tuo ordine. Accanto a ciascun prodotto, c'è un",
  order_summary_label: "etichetta",
  order_summary_subtitle_2:
    'che indica lo stato del prodotto: "obbligatorio", "non completato" o "completato". Questo ti aiuta a identificare facilmente quali elementi devi completare prima di finalizzare l\'ordine.',
  customization_section_title: "Sezione di Personalizzazione",
  customization_section_subtitle_1:
    "Questa sezione ti consente di personalizzare completamente il tuo prodotto, includendo:",
  customization_section_highlight_1: "Tipo di Lenti",
  customization_section_highlight_2: "Tipo di Montatura",
  customization_section_highlight_3: "Accessorio Funzionale",
  customization_section_highlight_4: "Clip di Design",
  customization_section_highlight_5: "astine",
  customization_section_subtitle_2:
    '. Ogni opzione mostra il suo stato di "obbligatorio", "non completato" o "completato", in modo che tu possa monitorare i progressi della tua personalizzazione.',
  client_info_card_title: "Carta Informazioni Cliente",
  client_info_card_subtitle_1:
    "Questa carta fornisce informazioni sul cliente associato all'appuntamento. Include dettagli come la data dell'appuntamento, il tipo di cliente (sia",
  client_info_card_highlight_1: "FLIPO",
  client_info_card_highlight_2: "OPTIC",
  client_info_card_subtitle_2:
    "), e le promozioni che si applicano a questo cliente. Questo ti aiuta a ottenere una visione chiara delle preferenze e dei vantaggi del cliente per il suo appuntamento.",
  product_configuration_card_title: "Carta di Configurazione del Prodotto",
  product_configuration_card_subtitle_1:
    "Questa carta mostra tutte le opzioni richieste per configurare il prodotto, che possono variare a seconda dei vari tipi. Puoi selezionare diverse caratteristiche e accessori per personalizzare il tuo prodotto in base alle tue esigenze specifiche.",
  product_configuration_panel_title:
    "Pannello di Configurazione degli Accessori",
  product_configuration_panel_subtitle_1:
    "Questo pannello ti consente di regolare in modo personalizzato le configurazioni degli accessori selezionati. Qui puoi visualizzare chiaramente le opzioni disponibili e impostare la quantità massima che puoi aggiungere alla tua selezione, assicurandoti di ottenere la configurazione esatta di cui hai bisogno.",
  product_configuration_panel_strong:
    "Fai clic sul pannello per scoprire più dettagli e opzioni.",
  product_personalize_panel_title: "Pannello di Personalizzazione Accessori",
  product_personalize_panel_subtitle_1:
    "Questo pannello offre due funzioni chiave:",
  product_personalize_function_1:
    '1. Pulsanti "+" e "-" che ti consentono di aumentare o ridurre la quantità dello stesso prodotto.',
  product_personalize_function_2:
    '2. Un pulsante "Personalizza" che ti permette di modificare il prodotto selezionato secondo le tue preferenze.',
  customize_button: "Personalizza",
  title_select_combination: "Scegli la tua combinazione",
  close_button: "Chiudi",
  without_stock: "Senza stock",
  Scroll_to_see_more_products: "Scorri per vedere più prodotti",
  order_comment_placeholder: "Aggiungi un commento al tuo ordine",
  order_comment_label: "Commento dell’ordine",
  payment_less_than_remaining: "Pagamento Inferior ao Resto",

  _comment_23: "BillingOrderPage",
  actions_table_orders_billing: "Azioni",
  to_mark_as_billing: "Segna come fatturato",
  enter_billin_number: "Inserisci il numero di fatturazione",
  billing_number: "Numero di fatturazione",
  enter_billing_number_placeholder: "Inserisci il numero di fatturazione",
  cancel_billing: "Annulla fatturazione",
  Accept_billing: "Accetta fatturazione",
  processing_please_wait: "Elaborazione in corso, attendere prego",
  order_marked_as_billed: "Ordine segnato come fatturato",
  payment_issue:
    "Ci dispiace che abbia avuto problemi con il pagamento della sua carta. Di seguito le offriamo una serie di raccomandazioni per evitare che questa situazione si ripeta:",
  card_active:
    "Verifica che la tua carta sia attiva e non sia scaduta. Puoi controllare lo stato della tua carta presso la tua banca o nell'app mobile della tua banca.",
  check_details:
    "Assicurati di aver inserito correttamente i dati della tua carta, come il numero, la data di scadenza e il codice di sicurezza. Verifica che non ci siano spazi o caratteri speciali tra i numeri.",
  check_balance:
    "Assicurati di avere saldo sufficiente sul tuo conto per effettuare il pagamento. Se la tua carta ha un limite di credito, verifica che non lo hai superato.",
  sms_verification:
    "Se la tua carta ha l'opzione di pagamento sicuro o verifica tramite SMS, assicurati di avere copertura e di ricevere il codice di conferma sul tuo telefono cellulare. Inserisci il codice entro il termine indicato e non condividerlo con nessuno.",
  blocked_card:
    "Se hai effettuato diversi tentativi di pagamento falliti, è possibile che la tua carta sia stata temporaneamente bloccata per motivi di sicurezza. In tal caso, contatta la tua banca per sbloccarla e poterla riutilizzare.",
  alternate_payment:
    "Se il problema persiste, puoi provare a pagare con un'altra carta o con un altro metodo di pagamento disponibile sul nostro sito web. Puoi anche contattare il nostro servizio clienti per ricevere assistenza.",
  try_again_message: "Riprova",
  transaction_cancelled: "Transazione annullata",
  transaction_declined: "Transazione rifiutata",
  m_not_flipo_mudle_alert: "Termina di configurare i dati",
  add_clip_modal_title: "Aggiungi Clip Aggiuntivo",
  add_clip_modal_description:
    "Puoi aggiungere un clip aggiuntivo al tuo ordine per",
  add_clip_modal_price: "10 euro.",
  add_clip_modal_add_button:
    'Fai clic su "Aggiungi all\'Ordine" per confermare.',
  completar_label: "Completare",
  completado_label: "Completato",
  no_aplica_label: "Non applicabile",
  OD: "(OD)",
  OI: "(OS)",
  D: "D",
  I: "S",
  confirm_all_data_lenses: "Assicurati di compilare tutti i campi",
  m_order_pending_table: "Non hai ordini in sospeso",
  m_modal_stock_sale: "Nome è obbligatorio",
  m_modal_stock_sale2: "I cognomi sono obbligatori",
  m_modal_stock_sale3: "Il telefono è obbligatorio",
  m_modal_stock_sale4: "Email non valida",
  m_modal_stock_sale5: "L'email è obbligatoria",
  sphere_required_field: "Campo richiesto per la sfera",
  sphere_value_field: "Valore non valido per la sfera",
  sphere_min_value: "Il valore minimo è -20 per la sfera",
  sphere_max_value: "Il valore massimo è 20 per la sfera",
  sphere_multiple_of_025:
    "Il valore deve essere un multiplo di 0.25 per la sfera",
  cylinder_required_field: "Campo richiesto per il cilindro",
  cylinder_value_field:
    "Il valore deve essere un numero valido per il cilindro",
  cylinder_min_value: "Il valore minimo è -6 per il cilindro",
  cylinder_max_value: "Il valore massimo è 6 per il cilindro",
  axis_required_field: "Campo richiesto per l'asse",
  axis_min_value: "Il valore minimo è 0 per l'asse",
  axis_max_value: "Il valore massimo è 180 per l'asse",
  mounting_data_required_field: "Campo richiesto per i dati di montaggio",
  mounting_data_min_value: "Il valore minimo è 20 per i dati di montaggio",
  mounting_data_max_value: "Il valore massimo è 45 per i dati di montaggio",
  height_data_required_field: "Campo richiesto per i dati di altezza",
  height_data_min_value: "Il valore minimo è 10 per i dati di altezza",
  height_data_max_value: "Il valore massimo è 40 per i dati di altezza",
  firstName_required: "Il nome è obbligatorio",
  lastName_required: "I cognomi sono obbligatori",
  phoneNumber_required: "Il telefono è obbligatorio",
  email_invalid: "Email non valida",
  email_required: "L'email è obbligatoria",

  _comment_24: "new product list",
  "0400001": "Aste Carey",
  "0400002": "Aste Navy",
  "0400003": "Aste Rioja",
  "0400004": "Aste Giallo Limone",
  "0400005": "Aste Rosa Pallido",
  "0400006": "Aste Verde Pistacchio",
  "0400007": "Aste Lilla Verypery",
  "0400008": "Aste Iced Coffee",
  "0400009": "Aste Verde Olive",
  "0400010": "Aste Valentina",
  "0400011": "Aste Red Sunset",
  "0400012": "Aste White Polar",
  "0400013": "Aste Green Forest",
  "0400014": "Aste Mogano",
  "0400015": "Aste Zebra",
  "0400016": "Aste Hawaii",
  "0400017": "Aste Marmo Blu",
  "0400018": "Aste Puzzle",
  "0400019": "Aste Brunch Vibes",
  "0400020": "Aste Sailor",
  "0400021": "Aste Kenya",
  "0400022": "Aste Highlands",
  "0400023": "Aste Nere",
  "0400024": "Aste Cioccolato",
  "0400025": "Aste Red Passion",
  "0400026": "Aste Valparaiso",
  "0400027": "Aste Black Flowers",
  "0200001": "Clip Original (Nilo) Solare Specchio Azzurro",
  "0200002": "Clip Original (Nilo) Solare Nero",
  "0200003": "Clip Original (Nilo) per la Guida Notturna",
  "0200004": "Clip Original (Nilo) Solare Specchio Arancione",
  "0200005": "Clip Original (Nilo) di Protezione dello Schermo",
  "0200006": "Clip Model C (Ivy) Solare Specchio Azzurro",
  "0200007": "Clip Model C (Ivy) Solare Nero",
  "0200008": "Clip Model C (Ivy) per la Guida Notturna",
  "0200009": "Clip Model C (Ivy) Solare Specchio Arancione",
  "0200010": "Clip Model C (Ivy) di Protezione dello Schermo",
  "0200011": "Clip Model A (Dante) Solare Specchio Azzurro",
  "0200012": "Clip Model A (Dante) Solare Nero",
  "0200013": "Clip Model A (Dante) per la Guida Notturna",
  "0200014": "Clip Model A (Dante) Solare Specchio Arancione",
  "0200015": "Clip Model A (Dante) di Protezione dello Schermo",
  "0200016": "Clip Model D (Siena) Solare Specchio Azzurro",
  "0200017": "Clip Model D (Siena) Solare Nero",
  "0200018": "Clip Model D (Siena) per la Guida Notturna",
  "0200019": "Clip Model D (Siena) Solare Specchio Arancione",
  "0200020": "Clip Model D (Siena) di Protezione dello Schermo",
  "0300014 + 0500011":
    "Clip Original (Nilo) Solare Azzurro Degradato Polarizzato",
  "0300014 + 0500012":
    "Clip Original (Nilo) Solare Marrone Degradato Polarizzato",
  "0300014 + 0500013": "Clip Original (Nilo) Solare Vino Degradato Polarizzato",
  "0300014 + 0500014":
    "Clip Original (Nilo) Solare Rame Riflettente Polarizzato",
  "0300014 + 0500015":
    "Clip Original (Nilo) Solare Fucsia Riflettente Polarizzato",
  "0300014 + 0500016":
    "Clip Original (Nilo) Solare Viola Riflettente Polarizzato",
  "0300014 + 0500017":
    "Clip Original (Nilo) Solare Specchio Riflettente Polarizzato",
  "0300014 + 0500018":
    "Clip Original (Nilo) Solare Verde Riflettente Polarizzato",
  "0300014 + 0500019": "Clip Original (Nilo) Solare Azzurro Chiaro Polarizzato",
  "0300014 + 0500020": "Clip Original (Nilo) Solare Lilla Chiaro Polarizzato",
  "0300037 + 0500021":
    "Clip Model C (Ivy) Solare Azzurro Degradato Polarizzato",
  "0300037 + 0500022":
    "Clip Model C (Ivy) Solare Marrone Degradato Polarizzato",
  "0300037 + 0500023": "Clip Model C (Ivy) Solare Vino Degradato Polarizzato",
  "0300037 + 0500024": "Clip Model C (Ivy) Solare Rame Riflettente Polarizzato",
  "0300037 + 0500025":
    "Clip Model C (Ivy) Solare Fucsia Riflettente Polarizzato",
  "0300037 + 0500026":
    "Clip Model C (Ivy) Solare Viola Riflettente Polarizzato",
  "0300037 + 0500027":
    "Clip Model C (Ivy) Solare Specchio Riflettente Polarizzato",
  "0300037 + 0500028":
    "Clip Model C (Ivy) Solare Verde Riflettente Polarizzato",
  "0300037 + 0500029": "Clip Model C (Ivy) Solare Azzurro Chiaro Polarizzato",
  "0300037 + 0500030": "Clip Model C (Ivy) Solare Lilla Chiaro Polarizzato",
  "0300060 + 0500031":
    "Clip Model A (Dante) Solare Azzurro Degradato Polarizzato",
  "0300060 + 0500037":
    "Clip Model A (Dante) Solare Marrone Degradato Polarizzato",
  "0300060 + 0500038": "Clip Model A (Dante) Solare Vino Degradato Polarizzato",
  "0300060 + 0500039":
    "Clip Model A (Dante) Solare Rame Riflettente Polarizzato",
  "0300060 + 0500040":
    "Clip Model A (Dante) Solare Fucsia Riflettente Polarizzato",
  "0300060 + 0500041":
    "Clip Model A (Dante) Solare Viola Riflettente Polarizzato",
  "0300060 + 0500042":
    "Clip Model A (Dante) Solare Specchio Riflettente Polarizzato",
  "0300060 + 0500043":
    "Clip Model A (Dante) Solare Verde Riflettente Polarizzato",
  "0300060 + 0500044": "Clip Model A (Dante) Solare Azzurro Chiaro Polarizzato",
  "0300060 + 0500045": "Clip Model A (Dante) Solare Lilla Chiaro Polarizzato",
  "0300083 + 0500051":
    "Clip Model D (Siena) Solare Azzurro Degradato Polarizzato",
  "0300083 + 0500052":
    "Clip Model D (Siena) Solare Marrone Degradato Polarizzato",
  "0300083 + 0500053": "Clip Model D (Siena) Solare Vino Degradato Polarizzato",
  "0300083 + 0500054":
    "Clip Model D (Siena) Solare Rame Riflettente Polarizzato",
  "0300083 + 0500055":
    "Clip Model D (Siena) Solare Fucsia Riflettente Polarizzato",
  "0300083 + 0500056":
    "Clip Model D (Siena) Solare Viola Riflettente Polarizzato",
  "0300083 + 0500057":
    "Clip Model D (Siena) Solare Specchio Riflettente Polarizzato",
  "0300083 + 0500058":
    "Clip Model D (Siena) Solare Verde Riflettente Polarizzato",
  "0300083 + 0500059": "Clip Model D (Siena) Solare Azzurro Chiaro Polarizzato",
  "0300083 + 0500060": "Clip Model D (Siena) Solare Lilla Chiaro Polarizzato",
  "0300001": "Clip Original (Nilo) Carey",
  "0300002": "Clip Original (Nilo) Navy",
  "0300003": "Clip Original (Nilo) Rioja",
  "0300004": "Clip Original (Nilo) Giallo Limone",
  "0300005": "Clip Original (Nilo) Rosa Pallido",
  "0300006": "Clip Original (Nilo) Verde Pistacchio",
  "0300007": "Clip Original (Nilo) Lilla Verypery",
  "0300008": "Clip Original (Nilo) Iced Coffee",
  "0300009": "Clip Original (Nilo) Verde Olive",
  "0300010": "Clip Original (Nilo) Valentina",
  "0300011": "Clip Original (Nilo) Red Sunset",
  "0300012": "Clip Original (Nilo) White Polar",
  "0300013": "Clip Original (Nilo) Green Forest",
  "0300014": "Clip Original (Nilo) Base Nera",
  "0300015": "Clip Original (Nilo) Mogano",
  "0300016": "Clip Original (Nilo) Zebra",
  "0300017": "Clip Original (Nilo) Hawaii",
  "0300018": "Clip Original (Nilo) Marmo Blu",
  "0300019": "Clip Original (Nilo) Puzzle",
  "0300020": "Clip Original (Nilo) Brunch Vibes",
  "0300021": "Clip Original (Nilo) Sailor",
  "0300022": "Clip Original (Nilo) Kenya",
  "0300023": "Clip Original (Nilo) Highlands",
  "0300024": "Clip Model C (Ivy) Carey",
  "0300025": "Clip Model C (Ivy) Navy",
  "0300026": "Clip Model C (Ivy) Rioja",
  "0300027": "Clip Model C (Ivy) Giallo Limone",
  "0300028": "Clip Model C (Ivy) Rosa Pallido",
  "0300029": "Clip Model C (Ivy) Verde Pistacchio",
  "0300030": "Clip Model C (Ivy) Lilla Verypery",
  "0300031": "Clip Model C (Ivy) Iced Coffee",
  "0300032": "Clip Model C (Ivy) Verde Olive",
  "0300033": "Clip Model C (Ivy) Valentina",
  "0300034": "Clip Model C (Ivy) Red Sunset",
  "0300035": "Clip Model C (Ivy) White Polar",
  "0300036": "Clip Model C (Ivy) Green Forest",
  "0300037": "Clip Model C (Ivy) Base Nera",
  "0300038": "Clip Model C (Ivy) Mogano",
  "0300039": "Clip Model C (Ivy) Zebra",
  "0300040": "Clip Model C (Ivy) Hawaii",
  "0300041": "Clip Model C (Ivy) Marmo Blu",
  "0300042": "Clip Model C (Ivy) Puzzle",
  "0300043": "Clip Model C (Ivy) Brunch Vibes",
  "0300044": "Clip Model C (Ivy) Sailor",
  "0300045": "Clip Model C (Ivy) Kenya",
  "0300046": "Clip Model C (Ivy) Highlands",
  "0300047": "Clip Model A (Dante) Carey",
  "0300048": "Clip Model A (Dante) Navy",
  "0300049": "Clip Model A (Dante) Rioja",
  "0300050": "Clip Model A (Dante) Giallo Limone",
  "0300051": "Clip Model A (Dante) Rosa Pallido",
  "0300052": "Clip Model A (Dante) Verde Pistacchio",
  "0300053": "Clip Model A (Dante) Lilla Verypery",
  "0300054": "Clip Model A (Dante) Iced Coffee",
  "0300055": "Clip Model A (Dante) Verde Olive",
  "0300056": "Clip Model A (Dante) Valentina",
  "0300057": "Clip Model A (Dante) Red Sunset",
  "0300058": "Clip Model A (Dante) White Polar",
  "0300059": "Clip Model A (Dante) Green Forest",
  "0300060": "Clip Model A (Dante) Base Nera",
  "0300061": "Clip Model A (Dante) Mogano",
  "0300062": "Clip Model A (Dante) Zebra",
  "0300063": "Clip Model A (Dante) Hawaii",
  "0300064": "Clip Model A (Dante) Marmo Blu",
  "0300065": "Clip Model A (Dante) Puzzle",
  "0300066": "Clip Model A (Dante) Brunch Vibes",
  "0300067": "Clip Model A (Dante) Sailor",
  "0300068": "Clip Model A (Dante) Kenya",
  "0300069": "Clip Model A (Dante) Highlands",
  "0300070": "Clip Model D (Siena) Carey",
  "0300071": "Clip Model D (Siena) Navy",
  "0300072": "Clip Model D (Siena) Rioja",
  "0300073": "Clip Model D (Siena) Giallo Limone",
  "0300074": "Clip Model D (Siena) Rosa Pallido",
  "0300075": "Clip Model D (Siena) Verde Pistacchio",
  "0300076": "Clip Model D (Siena) Lilla Verypery",
  "0300077": "Clip Model D (Siena) Iced Coffee",
  "0300078": "Clip Model D (Siena) Verde Olive",
  "0300079": "Clip Model D (Siena) Valentina",
  "0300080": "Clip Model D (Siena) Red Sunset",
  "0300081": "Clip Model D (Siena) White Polar",
  "0300082": "Clip Model D (Siena) Green Forest",
  "0300083": "Clip Model D (Siena) Base Nera",
  "0300084": "Clip Model D (Siena) Mogano",
  "0300085": "Clip Model D (Siena) Zebra",
  "0300086": "Clip Model D (Siena) Hawaii",
  "0300087": "Clip Model D (Siena) Marmo Blu",
  "0300088": "Clip Model D (Siena) Puzzle",
  "0300089": "Clip Model D (Siena) Brunch Vibes",
  "0300090": "Clip Model D (Siena) Sailor",
  "0300091": "Clip Model D (Siena) Kenya",
  "0300092": "Clip Model D (Siena) Highlands",
  "0300093": "Clip Original (Nilo) Cioccolato",
  "0300094": "Clip Original (Nilo) Red Passion",
  "0300095": "Clip Original (Nilo) Valparaiso",
  "0300096": "Clip Original (Nilo) Black Flowers",
  "0300097": "Clip Model C (Ivy) Cioccolato",
  "0300098": "Clip Model C (Ivy) Red Passion",
  "0300099": "Clip Model C (Ivy) Valparaiso",
  "0300100": "Clip Model C (Ivy) Black Flowers",
  "0300101": "Clip Model A (Dante) Cioccolato",
  "0300102": "Clip Model A (Dante) Red Passion",
  "0300103": "Clip Model A (Dante) Valparaiso",
  "0300104": "Clip Model A (Dante) Black Flowers",
  "0300105": "Clip Model D (Siena) Cioccolato",
  "0300106": "Clip Model D (Siena) Red Passion",
  "0300107": "Clip Model D (Siena) Valparaiso",
  "0300108": "Clip Model D (Siena) Black Flowers",

  _comment_25: "new frames",
  "0100001": "Montatura Originale (Nilo) Nera",
  "0100002": "Montatura Originale (Nilo) Chiara",
  "0100003": "Montatura Modello C (Ivy) Nera",
  "0100004": "Montatura Modello C (Ivy) Chiara",
  "0100005": "Montatura Modello A (Dante) Nera",
  "0100006": "Montatura Modello A (Dante) Chiara",
  "0100007": "Montatura Modello D (Siena) Nera",
  "0100008": "Montatura Modello D (Siena) Chiara",
};
